[analytic.metadata]
categories = ["detect"]
confidence = "medium"
contributors = ["Tony Lambert"]
created_date = "01/07/2019"
description = "Identifies usage of ``ntdsutil.exe`` to export an Active Directory database to disk."
id = "19d59f40-12fc-11e9-8d76-4d6bb837cda4"
name = "AD Dumping via Ntdsutil.exe"
os = ["windows"]
tags = ["atomicblue"]
tactics = ["Credential Access"]
techniques = ["T1003"]
updated_date = "01/07/2019"

[analytic]
query = '''
file where file_name == "ntds.dit" and process_name == "ntdsutil.exe"
'''