[analytic.metadata]
categories = ["detect", "hunt"]
confidence = "low"
contributors = ["Endgame"]
created_date = "11/30/2018"
description = "Identifies creation of local users via the ``net.exe`` command."
id = "014c3f51-89c6-40f1-ac9c-5688f26090ab"
name = "User Account Creation"
os = "windows"
references = []
tactics = ["Persistence", "Credential Access"]
tags = ["atomicblue"]
techniques = ["T1136"]
updated_date = "11/30/2018"

[analytic]
query = '''
process where subtype.create and
  (process_name == "net.exe" or (process_name == "net1.exe" and parent_process_name != "net.exe")) and
  command_line == "* user */ad*"
'''
